[project]
name = "tandem-model"
version = "0.1.0"
description = "TANDEM (Turbulence ANd DEficit Momentum) wake model"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.4",
    "matplotlib>=3.7.5",
    "jinja2>=3.1.4,<4",
    "polars>=0.19",
    "ipykernel>=6.29.5",
    "scipy>=1.10.1",
    "seaborn>=0.13.2",
    "pyarrow>=20.0.0",
    "xarray>=2023.1",
    "foreach>=0.4.0",
    "mitwindfarm",
    "streamtube @ git+https://github.com/kirbyh/streamtube",
    "padeopsio @ git+https://github.com/Howland-Lab/padeopsIO@main",
]

[project.optional-dependencies]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["tandem_model"]

[tool.uv.sources]
mitwindfarm = { path = "../analysis_code/MITWindfarm" }
